using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class InputCharacters 
{
	public static List<KeyCode> modifierKeys = new List<KeyCode>(){
		KeyCode.RightShift,
		KeyCode.LeftShift,
		KeyCode.RightControl,
		KeyCode.LeftControl,
		KeyCode.RightAlt,
		KeyCode.LeftAlt,
		//KeyCode.RightApple,
		//KeyCode.RightApple,
		KeyCode.LeftCommand,
		KeyCode.RightCommand,
		//KeyCode.LeftWindows,
		//KeyCode.RightWindows
	};

	public static List<KeyCode> actionKeys = new List<KeyCode>(){
		KeyCode.Backspace,
		KeyCode.Clear,
		KeyCode.Pause,
		KeyCode.Escape,
		KeyCode.Delete,
		KeyCode.UpArrow,
		KeyCode.DownArrow,
		KeyCode.RightArrow,
		KeyCode.LeftArrow,
		KeyCode.Insert,
		KeyCode.Home,
		KeyCode.End,
		KeyCode.PageUp,
		KeyCode.PageDown,
		KeyCode.CapsLock,
		KeyCode.ScrollLock,
		KeyCode.Print,
		KeyCode.Break,
		KeyCode.Menu
	};
	
	public static Dictionary<KeyCode, string> typedChars = new Dictionary<KeyCode, string>(){
		{ KeyCode.A, "a" },
		{ KeyCode.B, "b" },
		{ KeyCode.C, "c" },
		{ KeyCode.D, "d" },
		{ KeyCode.E, "e" },
		{ KeyCode.F, "f" },
		{ KeyCode.G, "g" },
		{ KeyCode.H, "h" },
		{ KeyCode.I, "i" },
		{ KeyCode.J, "j" },
		{ KeyCode.K, "k" },
		{ KeyCode.L, "l" },
		{ KeyCode.M, "m" },
		{ KeyCode.N, "n" },
		{ KeyCode.O, "o" },
		{ KeyCode.P, "p" },
		{ KeyCode.Q, "q" },
		{ KeyCode.R, "r" },
		{ KeyCode.S, "s" },
		{ KeyCode.T, "t" },
		{ KeyCode.U, "u" },
		{ KeyCode.V, "v" },
		{ KeyCode.W, "w" },
		{ KeyCode.X, "x" },
		{ KeyCode.Y, "y" },
		{ KeyCode.Z, "z" },
		{ KeyCode.Tab, "\t" },
		{ KeyCode.Return, "\n" },
		{ KeyCode.Space, " " },
		{ KeyCode.Exclaim, "!" },
		{ KeyCode.DoubleQuote, "\"" },
		{ KeyCode.Hash, "#" },
		{ KeyCode.Dollar, "$" },
		{ KeyCode.Ampersand, "&" },
		{ KeyCode.Quote, "'" },
		{ KeyCode.LeftParen, "(" },
		{ KeyCode.RightParen, ")" },
		{ KeyCode.Asterisk, "*" },
		{ KeyCode.Plus, "+" },
		{ KeyCode.Comma, "," },
		{ KeyCode.Minus, "-" },
		{ KeyCode.Period, "." },
		{ KeyCode.Slash, "/" },
		{ KeyCode.Alpha0, "0" },
		{ KeyCode.Alpha1, "1" },
		{ KeyCode.Alpha2, "2" },
		{ KeyCode.Alpha3, "3" },
		{ KeyCode.Alpha4, "4" },
		{ KeyCode.Alpha5, "5" },
		{ KeyCode.Alpha6, "6" },
		{ KeyCode.Alpha7, "7" },
		{ KeyCode.Alpha8, "8" },
		{ KeyCode.Alpha9, "9" },
		{ KeyCode.Colon, ":" },
		{ KeyCode.Semicolon, ";" },
		{ KeyCode.Less, "<" },
		{ KeyCode.Equals, "=" },
		{ KeyCode.Greater, ">" },
		{ KeyCode.Question, "?" },
		{ KeyCode.At, "@" },
		{ KeyCode.LeftBracket, "[" },
		{ KeyCode.Backslash, "\\" },
		{ KeyCode.RightBracket, "]" },
		{ KeyCode.Caret, "^" },
		{ KeyCode.Underscore, "_" },
		{ KeyCode.BackQuote, "`" },
		{ KeyCode.AltGr, "~" },
		{ KeyCode.Keypad0, "0" },
		{ KeyCode.Keypad1, "1" },
		{ KeyCode.Keypad2, "2" },
		{ KeyCode.Keypad3, "3" },
		{ KeyCode.Keypad4, "4" },
		{ KeyCode.Keypad5, "5" },
		{ KeyCode.Keypad6, "6" },
		{ KeyCode.Keypad7, "7" },
		{ KeyCode.Keypad8, "8" },
		{ KeyCode.Keypad9, "9" },
		{ KeyCode.KeypadPeriod, "." },
		{ KeyCode.KeypadDivide, "/" },
		{ KeyCode.KeypadMultiply, "*" },
		{ KeyCode.KeypadMinus, "-" },
		{ KeyCode.KeypadPlus, "+" },
		{ KeyCode.KeypadEnter, "\n" },
		{ KeyCode.KeypadEquals, "=" }
	};

	public static Dictionary<KeyCode, string> shiftedSpecialChars = new Dictionary<KeyCode, string>(){
		{ KeyCode.Slash, "?" },
		{ KeyCode.Alpha0, ")" },
		{ KeyCode.Alpha1, "!" },
		{ KeyCode.Alpha2, "@" },
		{ KeyCode.Alpha3, "#" },
		{ KeyCode.Alpha4, "$" },
		{ KeyCode.Alpha5, "%" },
		{ KeyCode.Alpha6, "^" },
		{ KeyCode.Alpha7, "&" },
		{ KeyCode.Alpha8, "*" },
		{ KeyCode.Alpha9, "(" },
		{ KeyCode.Quote, "\"" },
		{ KeyCode.Semicolon, ":" },
		{ KeyCode.Equals, "+" },
		{ KeyCode.Minus, "_" },
		{ KeyCode.BackQuote, "~" },
		{ KeyCode.Comma, "<" },
		{ KeyCode.Period, ">" },
		{ KeyCode.RightBracket, "}" },
		{ KeyCode.LeftBracket, "{" },
		{ KeyCode.Backslash, "|" }

	};
}
